version: '3.4'

services:
  database:
    container_name: database
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: database
        target: /var/opt/mssql

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
        - "27017:27017"
    volumes:
        - 'data:/data/db'

  api:
    container_name: WOC_API
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - mongodb
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=9000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
        - ~/.aspnet/https:/https:ro

volumes:
  database:
  data: